language: cpp
sudo: false
cache: apt

addons:
    apt:
        packages:
        - verilator


branches:
    only:
        - master
        - dev_travis

jobs:
    include:
        - stage: sw_build
          name: build software
          script: make

