language: cpp
sudo: false
cache: apt

dist: focal
addons:
    apt:
        packages:
        - verilator
        - libsystemc-dev



branches:
    only:
        - master
        - dev_travis

install: make

jobs:
    include:
        - stage: test
          name: run the testbench
          script:
              - ./simulation.x 0
              - ./simulation.x
              - ./simulation.x 19982312


