= Mersenne-twister-hardware 

image:https://img.shields.io/github/license/Jeudine/Mersenne-twister-hardware?style=flat-square[license BSD-3-Clause, link=https://opensource.org/licenses/BSD-3-Clause]

A flexible hardware module written in SystemVerilog which implements the Mersene twister (using a 32-bit word length). A test bench written in SystemC, which uses Verilator was created in order to verify and simulate the hardware module.

== Installation

Clone the repository:
[source, shell]
----
git clone git@github.com:Jeudine/Mersenne-twister-hardware.git
----

If you will be using the simulation and the test bench, download https://www.accellera.org/downloads/standards/systemc[SystemC] and https://www.veripool.org/wiki/verilator[Verilator].

Once downloaded, run `make` in the root of the repository to build the project.

== Usage

The top module is defined with the following parameters and ports:

[source, verilog]
----
module MTwister #(parameter
    N = 624, // degree of recurrence
    M = 397, // middle word
    R = 31, // separation point of one word
    A = 32'h9908B0DF, // coefficients of the rational normal form twist matrix
    U = 11, // shift size used in the tempering process
    D = 32'hFFFFFFFF, // XOR mask used in the tempering process
    S = 7, // shift size used in tempering process
    B = 32'h9D2C5680, // XOR mask used in the tempering process
    T = 15, // shift size used in tempering process
    C = 32'hEFC60000, // XOR mask used in the tempering process
    L = 18, // shift size used in tempering process
    F = 1812433253 // initialization parameter
) (
    input clk, rst, trig,
    input [31:0] seed,
    output [31:0] r_num,
    output ready
);
----

The reset (`rst`) is synchronous and positive-logic. Once `rst` becomes low, the module is initialized with the value of the `seed` signal.

During the *Initialisation* and the *Generation*, the signal `ready` is low. This signal is high when numbers are ready to be extracted.

When `ready` is high, each time `trig` will be high during a rising edge of `clk`, a new random number will be extracted the next rising edge of `clk` on the `r_num` output.

== Simulation and test bench

Run `./simulation.x` to execute the simulation.

Two `.vcd` trace files will be generated:

* `simu_trace.vcd` contains all the input/output signals of the *MTwister* module and also those of the *MTwister_func* sc_module (a functional module of the Mersenne Twsiter written in c++ used to verify the correctness of *MTwister*).

* `debug_trace.vcd` contains all the internal signals of the *MTwister* module. This trace file makes debug easier.
